/**
 * WCM Mission Control — Documentation Center.
 * Release configuration.
 *
 * GitHub main (scoppolabi-ux/WCM-LAB) is the source of truth.
 * DOCX/PDF are derived releases, NOT authority.
 */

export const REPO_OWNER = 'scoppolabi-ux';
export const REPO_NAME = 'WCM-LAB';
export const REPO_REF = 'main';

export const RELEASE_DIR = 'public/wcm/documentation/releases';

/** Minimum plausible size (bytes) for a generated binary artifact. */
export const MIN_DOCX_BYTES = 4000;
export const MIN_PDF_BYTES = 4000;

export const DOCUMENTS = [
  {
    document_id: 'wcm-technical-reference',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: 'WCM Technical Reference',
    audience: 'Stakeholder tecnico, developer, architect, partner AI/automation',
    description:
      'Riferimento tecnico end-to-end del Wise Centric Model: runtime durevole, state/projector deterministici, assurance, authority, learning, persistent mutation safety, flow block e Documentation System.',
    version: 'V0.5',
    master_date: '2026-08-24',
    status: 'ACTIVE',
    source_path: 'wcm/documentation/WCM_TECHNICAL_REFERENCE_V0_5.md',
    download_basename: 'WCM_Technical_Reference_V0_5',
    bootstrap_file: 'WCM_TECHNICAL_REFERENCE_V0_5.md',
    bootstrap_sha: '11a025570bb737ed08b0aeddb3b34f7b4e0111de',
    visual_qa_status: 'PASS',
    docx_page_count: 8,
    pdf_page_count: 9,
  },
  {
    document_id: 'wcm-executive-client-guide',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: 'WCM Executive / Client Guide',
    audience: 'Clienti, partner, management, investitori e interlocutori non tecnici',
    description:
      'Guida esecutiva al metodo WCM: continuità organizzativa, memoria controllata, determinismo selettivo, authority umana, automazioni spiegabili e field validation su PRIMA DI NOI.',
    version: 'V0.5',
    master_date: '2026-08-24',
    status: 'ACTIVE',
    source_path: 'wcm/documentation/WCM_EXECUTIVE_CLIENT_GUIDE_V0_5.md',
    download_basename: 'WCM_Executive_Client_Guide_V0_5',
    bootstrap_file: 'WCM_EXECUTIVE_CLIENT_GUIDE_V0_5.md',
    bootstrap_sha: 'ac8bf70eea05eefd545e7e375c84fd68cff12663',
    visual_qa_status: 'PASS',
    docx_page_count: 6,
    pdf_page_count: 7,
  },
  {
    document_id: 'wcm-user-manual',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: 'WCM User Manual',
    audience: 'Utilizzatori WCM, owner, Board e persone senza background tecnico',
    description:
      'Manuale discorsivo per usare WCM: Mission Control, Needs e Pending, heartbeat, gate, Knowledge Health, assurance, learning, documentazione e cosa richiede davvero l’utente.',
    version: 'V0.6',
    master_date: '2026-08-24',
    status: 'ACTIVE',
    source_path: 'wcm/documentation/WCM_USER_MANUAL_V0_6.md',
    download_basename: 'WCM_User_Manual_V0_6',
    bootstrap_file: 'WCM_USER_MANUAL_V0_6.md',
    bootstrap_sha: '80d886da68e537710826849c3b5e2efc8499291d',
    visual_qa_status: 'PASS',
    docx_page_count: 11,
    pdf_page_count: 14,
  },
  {
    document_id: 'wcm-process-memory-book-ch01',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 1,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '01 — Perché esiste WCM',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Perché una conversazione intelligente non è ancora un’organizzazione e quale problema prova a risolvere WCM.',
    version: 'FROZEN-01',
    master_date: '2026-08-25',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/01_perche_esiste_wcm.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_01_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH01.md',
    bootstrap_sha: '8fb8ec3d8f5e20d6ab1a035c88eeeb053813abe6',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch02',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 2,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '02 — I mattoni fondamentali',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Il vocabolario fondamentale del WCM: dati, conoscenza, stato, authority, processi, protocolli, nodi, indici, determinismo e idempotenza.',
    version: 'FROZEN-02',
    master_date: '2026-08-25',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/02_mattoni_fondamentali.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_02_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH02.md',
    bootstrap_sha: '2f2bac9002a45d450fea6a7471d57df60e6b3a73',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch03',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 3,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '03 — Perché una sola memoria non basta',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'La Dual Memory Architecture: Working Memory e Persistent Organizational Memory, consolidation e selective retrieval.',
    version: 'FROZEN-03',
    master_date: '2026-08-25',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/03_perche_una_sola_memoria_non_basta.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_03_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH03.md',
    bootstrap_sha: '70deb1b53c657af617cf354a893125506e26662a',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch04',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 4,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '04 — Working Memory: la memoria viva',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Cosa appartiene alla memoria viva, cosa può restarvi e quali delta devono essere consolidati nella memoria organizzativa.',
    version: 'FROZEN-04',
    master_date: '2026-08-26',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/04_working_memory.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_04_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH04.md',
    bootstrap_sha: '76c6a2daa268f74127117d31496c2adb9b2fcf48',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch05',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 5,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '05 — Persistent Organizational Memory: la memoria dell’organizzazione',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Come WCM rende durevole conoscenza, stato, decisioni, evidence e learning senza trasformare la memoria in un archivio indiscriminato.',
    version: 'FROZEN-05',
    master_date: '2026-08-28',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/05_persistent_organizational_memory.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_05_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH05.md',
    bootstrap_sha: 'eb3219d4169e0f7f960a27437a4f53558dd6a675',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch06',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 6,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '06 — Il ciclo tra le due memorie',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Il ciclo completo della Dual Memory: delta detection, classification, consolidation, assurance e selective retrieval.',
    version: 'FROZEN-06',
    master_date: '2026-08-28',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/06_ciclo_dual_memory.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_06_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH06.md',
    bootstrap_sha: '2b56e3e810e388510688cedf3db3e6bb532a1dcc',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch07',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 7,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '07 — L’architettura a nodi',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Perché la memoria WCM evolve da raccolta di file a rete di nodi identificabili, tipizzati, governati e collegabili.',
    version: 'FROZEN-07',
    master_date: '2026-08-28',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/07_architettura_a_nodi.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_07_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH07.md',
    bootstrap_sha: '5af04f28bbd4f2d77dae1777f1e6e148fb538cd7',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch08',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 8,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '08 — Le sinapsi: le relazioni tra i nodi',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Come WCM rappresenta relazioni tipizzate tra nodi, Impact Set, orphan control, relationship validity e Knowledge Health.',
    version: 'FROZEN-08',
    master_date: '2026-08-28',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/08_sinapsi_relazioni_tra_nodi.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_08_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH08.md',
    bootstrap_sha: 'b1dc1641f1dd76a72dc92071e511f0adcd45fe02',
    visual_qa_status: 'PENDING',
  },
  {
    document_id: 'wcm-process-memory-book-ch09',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 9,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '09 — Il problema della conoscenza troppo grande',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Perché una memoria organizzativa ricca diventa difficile da usare senza retrieval selettivo, source precedence e una mappa di navigazione.',
    version: 'FROZEN-09',
    master_date: '2026-08-29',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/09_il_problema_della_conoscenza_troppo_grande.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_09_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH09.md',
    bootstrap_sha: '5f585a57f434727e032a75139776d3cdaac8490f',
    visual_qa_status: 'PASS',
    docx_page_count: 24,
  },
  {
    document_id: 'wcm-process-memory-book-ch10',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 10,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '10 — Il Knowledge Navigation Layer',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Come WCM usa Entry Point, Index, metadata, Source Precedence, Progressive Retrieval e Stop Condition per trasformare una memoria grande in un percorso task-scoped.',
    version: 'FROZEN-10',
    master_date: '2026-08-29',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/10_knowledge_navigation_layer.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_10_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH10.md',
    bootstrap_sha: 'ad2e0a5fc2265b0d37c7d0506cfe6cb7aa9c9830',
    visual_qa_status: 'PASS',
    docx_page_count: 22,
  },
  {
    document_id: 'wcm-process-memory-book-ch11',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 11,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '11 — INDEX-FIRST spiegato passo per passo',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Walkthrough operativo del Progressive Retrieval WCM: L0–L3, Retrieval Gate, source authority, Delta Preferred e Stop When Sufficient.',
    version: 'FROZEN-11',
    master_date: '2026-08-29',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/11_index_first_spiegato_passo_per_passo.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_11_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH11.md',
    bootstrap_sha: '87b1a31e21afcf5a6e59afefc0ceb5645074f10e',
    visual_qa_status: 'PASS',
    docx_page_count: 18,
  },
  {
    document_id: 'wcm-process-memory-book-ch12',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 12,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '12 — Source Precedence — non tutte le informazioni valgono allo stesso modo',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Come WCM attribuisce peso alle fonti: authority, status, scope, tipo di fatto, precedence specifica per gli execution facts e divieto di silent conflict resolution.',
    version: 'FROZEN-12',
    master_date: '2026-08-29',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/12_source_precedence.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_12_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH12.md',
    bootstrap_sha: 'ddff24c1c1f5b8ecbca1aa969807ea740fa869ed',
    visual_qa_status: 'PASS',
    docx_page_count: null,
  },
  {
    document_id: 'wcm-process-memory-book-ch13',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 13,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '13 — Il Request Routing WCM',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Come WCM trasforma una richiesta in contesto operativo governato: intent, goal, scope, authority, resume, RUN/CHANGE, capability, processi e protocolli applicabili, context sufficiency, execution, stop condition e consolidation.',
    version: 'FROZEN-13',
    master_date: '2026-08-29',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/13_request_routing_wcm.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_13_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH13.md',
    bootstrap_sha: '9e181a5f07fc1d0261a2fe3792dec586318f2598',
    visual_qa_status: 'PASS',
    docx_page_count: 17,
  },
  {
    document_id: 'wcm-process-memory-book-ch14',
    document_kind: 'book_chapter',
    book_id: 'wcm-process-memory-book',
    chapter_number: 14,
    release_subdir: 'book/chapters',
    scope: 'wcm',
    project_id: null,
    project_label: null,
    title: '14 — Come WCM individua i protocolli da applicare',
    audience: 'Lettori tecnici e non tecnici del WCM Process & Memory Book',
    description: 'Come WCM individua i protocolli applicabili: protocol routing cognitivo e deterministico, trigger espliciti e derivati, relazioni processo/protocollo, guard exact event + exact hook, routing source e registry, service policy, anti-pattern e formula compatta.',
    version: 'FROZEN-14',
    master_date: '2026-08-29',
    status: 'FROZEN',
    source_path: 'wcm/documentation/process-memory-book/chapters/14_come_wcm_individua_i_protocolli_da_applicare.md',
    download_basename: 'WCM_Process_Memory_Book_Capitolo_14_FROZEN',
    bootstrap_file: 'WCM_PROCESS_MEMORY_BOOK_CH14.md',
    bootstrap_sha: 'f4c0b0ed64bb3fcdbd145317ebb61f774f78d34b',
    visual_qa_status: 'PASS',
    docx_page_count: 20,
  },
  {
    document_id: 'prima-di-noi-technical-reference',
    scope: 'project',
    project_id: 'prima-di-noi',
    project_label: 'PRIMA DI NOI',
    title: 'PRIMA DI NOI Technical Reference',
    audience: 'Tecnici, editori con background tecnologico, production architect, partner AI/editorial tech',
    description:
      'Riferimento tecnico dell’applicazione WCM a PRIMA DI NOI: Chapter Workflow, internal assurance dependency, delivery verificata, living knowledge, state/projector, heartbeat telemetry e Board Gate.',
    version: 'V0.2',
    master_date: '2026-08-24',
    status: 'ACTIVE',
    source_path: 'projects/prima-di-noi/documentation/PRIMA_DI_NOI_TECHNICAL_REFERENCE_V0_2.md',
    download_basename: 'PRIMA_DI_NOI_Technical_Reference_V0_2',
    bootstrap_file: 'PRIMA_DI_NOI_TECHNICAL_REFERENCE_V0_2.md',
    bootstrap_sha: '6e0ce024d4f14d472e9b139d0443a861d8477e62',
    visual_qa_status: 'PASS',
    docx_page_count: 8,
    pdf_page_count: 9,
  },
  {
    document_id: 'prima-di-noi-executive-editorial-partner-guide',
    scope: 'project',
    project_id: 'prima-di-noi',
    project_label: 'PRIMA DI NOI',
    title: 'PRIMA DI NOI Executive / Editorial Partner Guide',
    audience: 'Editori, autori, literary agent, studi editoriali, produttori di contenuti, partner publishing tech',
    description:
      'Case study editoriale AI-native governato: redazione virtuale persistente, maker/reviewer separation, continuity, author authority, assurance, delivery e osservabilità.',
    version: 'V0.2',
    master_date: '2026-08-24',
    status: 'ACTIVE',
    source_path: 'projects/prima-di-noi/documentation/PRIMA_DI_NOI_EXECUTIVE_EDITORIAL_PARTNER_GUIDE_V0_2.md',
    download_basename: 'PRIMA_DI_NOI_Executive_Editorial_Partner_Guide_V0_2',
    bootstrap_file: 'PRIMA_DI_NOI_EXECUTIVE_EDITORIAL_PARTNER_GUIDE_V0_2.md',
    bootstrap_sha: 'c9d239091c74e8b119a402adbb20e376f8737737',
    visual_qa_status: 'PASS',
    docx_page_count: 8,
    pdf_page_count: 8,
  },
  {
    document_id: 'prima-di-noi-user-manual',
    scope: 'project',
    project_id: 'prima-di-noi',
    project_label: 'PRIMA DI NOI',
    title: 'PRIMA DI NOI User Manual',
    audience: 'Author & Creative Director e utenti autorizzati, anche senza background tecnico',
    description:
      'Manuale discorsivo del progetto: ciclo del capitolo, Candidate e Board Report, mass control, continuity, assurance, heartbeat, approval/freeze, post-freeze e automazioni.',
    version: 'V0.2',
    master_date: '2026-08-24',
    status: 'ACTIVE',
    source_path: 'projects/prima-di-noi/documentation/PRIMA_DI_NOI_USER_MANUAL_V0_2.md',
    download_basename: 'PRIMA_DI_NOI_User_Manual_V0_2',
    bootstrap_file: 'PRIMA_DI_NOI_USER_MANUAL_V0_2.md',
    bootstrap_sha: '0e12a04df58402f439e0576e7d99bfacdb01739a',
    visual_qa_status: 'PASS',
    docx_page_count: 13,
    pdf_page_count: 15,
  },
];

export const STATIC_ASSETS = [
  {
    bootstrap_file: 'FIG-001A_DUAL_MEMORY_SIMPLE.svg',
    source_path: 'wcm/documentation/process-memory-book/figures/FIG-001A_DUAL_MEMORY_SIMPLE.svg',
    source_sha: '4a7700e4c2df3849b871f0fccc1436748e976158',
    release_path: 'book/figures/FIG-001A_DUAL_MEMORY_SIMPLE.svg',
  },
  {
    bootstrap_file: 'FIG-001B_DUAL_MEMORY_ARCHITECTURE.svg',
    source_path: 'wcm/documentation/process-memory-book/figures/FIG-001B_DUAL_MEMORY_ARCHITECTURE.svg',
    source_sha: '635bd681ac4ed2ab046c9478442592a0d30f4e63',
    release_path: 'book/figures/FIG-001B_DUAL_MEMORY_ARCHITECTURE.svg',
  },
  {
    bootstrap_file: 'FIG-002_FOUNDATIONAL_CONCEPT_MAP.svg',
    source_path: 'wcm/documentation/process-memory-book/figures/FIG-002_FOUNDATIONAL_CONCEPT_MAP.svg',
    source_sha: '28fe069c0998772629fe25edf036769120e0b6b1',
    release_path: 'book/figures/FIG-002_FOUNDATIONAL_CONCEPT_MAP.svg',
  },
  {
    bootstrap_file: 'FIG-003_WCM_NODE_ANATOMY.svg',
    source_path: 'wcm/documentation/process-memory-book/figures/FIG-003_WCM_NODE_ANATOMY.svg',
    source_sha: '647e18a202909b90265574c484111b4ff767f517',
    release_path: 'book/figures/FIG-003_WCM_NODE_ANATOMY.svg',
  },
  {
    bootstrap_file: 'FIG-004_WCM_SYNAPSE_NETWORK.svg',
    source_path: 'wcm/documentation/process-memory-book/figures/FIG-004_WCM_SYNAPSE_NETWORK.svg',
    source_sha: '88f2d9ffe2a1d6a8ef522aca0da642ef04bafd34',
    release_path: 'book/figures/FIG-004_WCM_SYNAPSE_NETWORK.svg',
  },
  {
    bootstrap_file: 'FIG-005_WCM_KNOWLEDGE_NAVIGATION_LAYER.svg',
    source_path: 'wcm/documentation/process-memory-book/figures/FIG-005_WCM_KNOWLEDGE_NAVIGATION_LAYER.svg',
    source_sha: 'baae714e90cf3e559253b81ff6f3d006e481ff91',
    release_path: 'book/figures/FIG-005_WCM_KNOWLEDGE_NAVIGATION_LAYER.svg',
  },
];

const chapter = (number, title, status = 'PLANNED', document_id = null) => ({
  number,
  title,
  status,
  document_id,
});

export const BOOKS = [
  {
    book_id: 'wcm-process-memory-book',
    scope: 'wcm',
    title: 'WCM — Libro dei Processi e della Memoria',
    subtitle: 'Come il Wise Centric Model comprende, ricorda, naviga, decide ed esegue',
    description: 'Manuale progressivo del metodo WCM. L’indice è approvato; i capitoli diventano consultabili nel Documentation Center quando raggiungono lo stato FROZEN.',
    status: 'IN_DEVELOPMENT',
    index_status: 'APPROVED',
    index_source_path: 'wcm/documentation/process-memory-book/BOOK_INDEX.md',
    index_source_sha: '7af9a6a5dea33df4df512fd3bd89b51346a6cc65',
    frozen_chapters: 13,
    sections: [
      { title: 'PARTE I — Capire WCM partendo da zero', chapters: [
        chapter(1, 'Perché esiste WCM', 'FROZEN', 'wcm-process-memory-book-ch01'),
        chapter(2, 'I mattoni fondamentali', 'FROZEN', 'wcm-process-memory-book-ch02'),
      ]},
      { title: 'PARTE II — L’architettura cognitiva: Dual Memory', chapters: [
        chapter(3, 'Perché una sola memoria non basta', 'FROZEN', 'wcm-process-memory-book-ch03'),
        chapter(4, 'Working Memory — la memoria viva', 'FROZEN', 'wcm-process-memory-book-ch04'),
        chapter(5, 'Persistent Organizational Memory — la memoria dell’organizzazione', 'FROZEN', 'wcm-process-memory-book-ch05'),
        chapter(6, 'Il ciclo tra le due memorie', 'FROZEN', 'wcm-process-memory-book-ch06'),
      ]},
      { title: 'PARTE III — La memoria non è un archivio: è una rete', chapters: [
        chapter(7, 'L’architettura a nodi', 'FROZEN', 'wcm-process-memory-book-ch07'), chapter(8, 'Le sinapsi: le relazioni tra i nodi', 'FROZEN', 'wcm-process-memory-book-ch08'),
      ]},
      { title: 'PARTE IV — INDEX-FIRST: come WCM trova quello che gli serve', chapters: [
        chapter(9, 'Il problema della conoscenza troppo grande', 'FROZEN', 'wcm-process-memory-book-ch09'),
        chapter(10, 'Il Knowledge Navigation Layer', 'FROZEN', 'wcm-process-memory-book-ch10'),
        chapter(11, 'INDEX-FIRST spiegato passo per passo', 'FROZEN', 'wcm-process-memory-book-ch11'),
        chapter(12, 'Source Precedence — non tutte le informazioni valgono allo stesso modo', 'FROZEN', 'wcm-process-memory-book-ch12'),
      ]},
      { title: 'PARTE V — Da una richiesta alle regole applicabili', chapters: [
        chapter(13, 'Il Request Routing WCM', 'FROZEN', 'wcm-process-memory-book-ch13'),
        chapter(14, 'Come WCM individua i protocolli da applicare'),
        chapter(15, 'Esempi di routing domain-agnostic'),
      ]},
      { title: 'PARTE VI — Il Libro dei Processi WCM', chapters: [
        chapter(16, 'Come leggere un processo WCM'),
        chapter(17, 'PROC-001 — Service Job Lifecycle'),
        chapter(18, 'PROC-002 — Workspace Pre-Sync'),
        chapter(19, 'PROC-003 — Deterministic Discovery & Durable Dispatch'),
        chapter(20, 'PROC-004 — Evidence → Baseline Promotion'),
        chapter(21, 'PROC-005 — Agent-Ready Context Bootstrap'),
        chapter(22, 'PROC-006 — Memory Consolidation & Consistency Loop'),
        chapter(23, 'PROC-007 — Project Bootstrap & Admission'),
        chapter(24, 'PROC-008 — Knowledge Integrity Assurance Loop'),
        chapter(25, 'PROC-009 — WCM Learning Loop'),
        chapter(26, 'PROC-010 — Documentation Continuity Loop'),
        chapter(27, 'PROC-011 — Deterministic State Reconciliation'),
        chapter(28, 'PROC-012 — WCM Change Propagation & Closure'),
      ]},
      { title: 'PARTE VII — Il Libro dei Protocolli WCM', chapters: [
        chapter(29, 'Processo vs Protocollo'),
        chapter(30, 'PROT-001 — Git & Working Tree Safety'),
        chapter(31, 'PROT-002 — Result Acceptance & Closure'),
        chapter(32, 'PROT-003 — Direct Before Delegate'),
        chapter(33, 'PROT-004 — Canonical Dispatch & Idempotency'),
        chapter(34, 'PROT-005 — Index-First Progressive Retrieval'),
        chapter(35, 'PROT-006 — Branch Ownership & Baseline Sync'),
        chapter(36, 'PROT-007 — Decision Change & Impact Analysis'),
        chapter(37, 'PROT-008 — Owner Source Intake Gate'),
        chapter(38, 'PROT-009 — Contiguous Workflow Execution'),
        chapter(39, 'PROT-010 — Mission Control Authenticated Authority Command'),
        chapter(40, 'PROT-011 — Capability Evidence Check Before Block'),
        chapter(41, 'PROT-012 — Verified Email Delivery & Idempotency'),
        chapter(42, 'PROT-013 — Knowledge Synapse & Health Standard'),
        chapter(43, 'PROT-014 — Method Experience Memory Standard'),
        chapter(44, 'PROT-015 — Documentation Impact & Publication Standard'),
        chapter(45, 'PROT-016 — Deterministic State & Projection Contract'),
        chapter(46, 'PROT-017 — Persistent Mutation Safety'),
        chapter(47, 'PROT-018 — Internal Async Dependency Resolution'),
        chapter(48, 'PROT-019 — WCM Change Closure Standard'),
        chapter(49, 'PROT-020 — WCM Technical Issue Tracking V1'),
      ]},
      { title: 'PARTE VIII — Come processi e protocolli lavorano insieme', chapters: [
        chapter(50, 'Il WCM non è una sequenza lineare'),
        chapter(51, 'La matrice Processi × Protocolli'),
        chapter(52, 'La mappa dei nodi procedurali'),
      ]},
      { title: 'PARTE IX — I loop fondamentali del WCM', chapters: [
        chapter(53, 'Operational Loop'), chapter(54, 'Memory Loop'), chapter(55, 'Immune Loop'),
        chapter(56, 'Learning Loop'), chapter(57, 'Documentation Continuity Loop'), chapter(58, 'Il ciclo completo'),
      ]},
      { title: 'PARTE X — Determinismo e cognizione', chapters: [
        chapter(59, 'Dove serve l’AI e dove non deve essere usata'),
        chapter(60, 'Cognitive Core vs Deterministic Core'),
      ]},
      { title: 'PARTE XI — Perché questa architettura è interessante', chapters: [
        chapter(61, 'I punti di forza'),
        chapter(62, 'Dove sta l’originalità dell’approccio WCM'),
        chapter(63, 'Limiti e maturità attuale'),
      ]},
    ],
    appendices: [
      ['A', 'Glossario completo WCM'], ['B', 'Mappa di tutti i Processi'], ['C', 'Mappa di tutti i Protocolli'],
      ['D', 'Matrice Processi × Protocolli'], ['E', 'Source Precedence Map'], ['F', 'Knowledge Node & Synapse Vocabulary'],
      ['G', 'Request → Protocol Routing Cheat Sheet'], ['H', 'Stati e Gate'], ['I', 'Schemi architetturali completi'],
      ['J', 'Legenda degli status'],
    ].map(([number, title]) => ({ number, title, status: 'PLANNED' })),
  },
];
